<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GeneticAlgorithm.Core</RootNamespace>
    <AssemblyName>GeneticAlgorithm.Core</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GeneticAlgorithm.Core.Tests" />
    <InternalsVisibleTo Include="GeneticAlgorithm.Application" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GeneticSharp" Version="3.1.4" />
  </ItemGroup>

</Project>
